### ISSUE TITLE
Weird compatibility issue with vanilla+ (RUI Error when loading into some game modes)

### ISSUE THREAD

**Issue by Rypha** [EladNLG/HUDRevampv2#6]
So when playing with vanilla + on vanilla servers with the mod i get rui related errors while loading in some modes 
![image](https://github.com/EladNLG/HUDRevampv2/assets/132854657/0b338305-36f7-4ee2-ac50-5f28fab0f709) also happens on the ctf game mode and i get kicked when i get these and cant even interact with the main menu anymore im at not sure if these 2 are the modes its happening on but good luck fixing that i really enjoy the d2 ui much better than the original ❤️❤️

**Comment by January-0002** [comment]
Yeah I have some weird issues with vanilla+ as well. Misaligned tactical and ordinance to the background and when scrolling through the mod configurator ingame, it throws out a game logic error. Probably just a limitation.

**Comment by headassbtw** [comment]
the mod isn't designed for vanilla+, it edits some scripts, and we used the northstar versions as a base, obviously

wontfix, and very low priority if possible to fix
